Develop
sinelamin/Nota-ToDo pull request #3
Opened 2024-08-21 14:49 UTC by sinelamin

2024-08-22 08:40 UTC, tamazyanarsen commented on src/app/feature/tasks/components/task-item/task-item.component.ts
> +  @Input() task!: Task;
убрать `!`
not null assertion

2024-08-23 07:25 UTC, sinelamin commented on src/app/feature/tasks/components/task-item/task-item.component.ts
> +  @Input() task!: Task;
исправил

2024-08-26 06:16 UTC, tamazyanarsen requested changes

2024-08-26 06:16 UTC, tamazyanarsen commented on src/app/feature/todo-input/todo-input.component.ts
> +      this.tasks = tasks;
не нужно отдельно сохранять в свойство класса данные из сервиса

оставляй в виде потока, а в html используй asyncPipe

2024-08-26 09:17 UTC, sinelamin commented on src/app/feature/todo-input/todo-input.component.ts
> +      this.tasks = tasks;
Исправил

2024-08-27 14:38 UTC, merged